"""A1-A5 contract regressions with one directly relevant mutation each."""

CASES = [
    ('F11', 'main.py', 'if type(wert) is not bool:', 'if False:',
     'test_main', 'test_eval_params_verlangt_json_booleans_statt_truthy_text'),
    ('F16', 'strategy_core.py', 'window = candles[-(period + 1):]',
     'window = candles[-period:]', 'test_strategy_core',
     'test_atr_kurzer_vorlauf_und_volles_fenster_gegen_unabhaengige_true_ranges'),
    ('F06', 'strategy_core.py',
     'd[0] <= d[1] / 3', 'd[0] >= d[1] / 3',
     'test_a2_flow', 'test_a2_f06_aggregated_spot_btc_is_compared_in_usd'),
    ('F07', 'flow_contract.py',
     'if i < 0:',
     'if i < 0 and not series.rows:',
     'test_a2_flow', 'test_a2_f07_prefix_first_oi_and_stale_age_live_backtest'),
    ('D02', 'flow_contract.py',
     'meta["coverage"] in ("observed", "carried")',
     'meta["coverage"] in ("observed", "carried", "missing", "stale")',
     'test_a2_flow', 'test_a2_d02_observed_zero_missing_and_stale_funding'),
    ('F08', 'strategy_core.py',
     'if set(slots) != {i * step for i in range(6)} or any(c is None for c in slots.values()):\n            continue\n        ordered = [slots[i * step] for i in range(6)]',
     'if len(slots) < 5 or any(c is None for c in slots.values()):\n            continue\n        ordered = [slots[i * step] for i in range(6) if i * step in slots]', 'test_a3_data',
     'test_utc_tageswechsel_erfordert_alle_sechs_abgeschlossenen_slots'),
    ('F14', 'coinalyze.py',
     'if not fehlende else set())\n    summe = {ts: sum(je_symbol[s][ts] for s in symbole)',
     'if True else set())\n    summe = {ts: sum(je_symbol[s][ts] for s in vorhanden)',
     'test_a3_data', 'test_angeforderter_markt_ohne_antwort_sperrt_summe_und_mittel'),
    ('F15', 'coinalyze.py',
     'sum(d["summe_v_usd"] for d in gruppen[k])',
     'sum(d["summe_v"] for d in gruppen[k])',
     'test_a3_data', 'test_btc_usd_volumenvergleich_nach_belegter_umrechnung'),
    ('F13', 'durable_delivery.py',
     "m['status'] in {'sending', 'uncertain'}",
     "m['status'] in {'sending'}",
     'test_a4_delivery', 'test_uncertain_blocks_new_command_ids_and_engine_dispatch'),
    ('F02-margin', 'derivative_accounting.py',
     "margin = sum((v['qty']*v['entry'] for v in lots.values()), Decimal(0)) if perp else Decimal(0)",
     'margin = Decimal(0)', 'test_a5_accounting', 'test_a5_two_full_shorts_bind_capital'),
    ('F02-funding', 'derivative_accounting.py',
     "legs = {k: -v['direction']*v['qty']*mark*rate for k,v in lots.items()}",
     "legs = {k: Decimal(0) for k,v in lots.items()}",
     'test_a5_accounting', 'test_a5_long_short_funding_signs_and_measured_zero'),
    ('F12-spot-gate', 'derivative_accounting.py',
     "if (cfg.get('instrument', SPOT) != SPOT or cfg.get('bias_short', False)",
     "if (False or cfg.get('bias_short', False)",
     'test_a6_regression', 'test_a6_v1_rejects_explicit_perpetual_before_replay'),
    ('T01-E41-order', 'main.py',
     "        if m41:\n            text = format_stop_rueckeroberung(m41)\n            stage('e41', m41['ts'], 0, m41, text,\n                  lambda text=text: send_text(text, dry_run=True))\n        for j, m in enumerate(m42):\n            text = format_ruecktest(m)\n            stage('e42', m['ts'], j, m, text,\n                  lambda text=text: send_text(text, dry_run=True))\n        if sigs:\n            for j, sig in enumerate(sigs):\n                stage('signal', sig['ts'], j, sig, format_signal(sig),\n                      lambda sig=sig: send_signals([sig], dry_run=True))",
     "        for j, m in enumerate(m42):\n            text = format_ruecktest(m)\n            stage('e42', m['ts'], j, m, text,\n                  lambda text=text: send_text(text, dry_run=True))\n        if sigs:\n            for j, sig in enumerate(sigs):\n                stage('signal', sig['ts'], j, sig, format_signal(sig),\n                      lambda sig=sig: send_signals([sig], dry_run=True))\n        if m41:\n            text = format_stop_rueckeroberung(m41)\n            stage('e41', m41['ts'], 0, m41, text,\n                  lambda text=text: send_text(text, dry_run=True))",
     'test_a6_regression', 'test_a6_e41_waiting_precedes_partial_sale_in_same_candle'),
]

REFRESH = [
    ('E443-legacy-inventory', 'position_state.py',
     "d.get('bestand_pct', min(100, pos.entry_pct or 0)) or 0",
     "d.get('bestand_pct', 0) or 0",
     'test_e443', 'test_zustand_ueberlebt_den_neustart_der_live_engine'),
    ('E41-buy-wait', 'strategy_core.py',
     'if _e41_sperre:\n            return False',
     'if False:\n            return False',
     'test_strategy_core', 'test_e41_kein_nachkauf_waehrend_des_wartens_und_der_rueckeroberung'),
    ('E41-message-missing', 'main.py',
     "        if m41:\n            text = format_stop_rueckeroberung(m41)",
     "        if False:\n            text = format_stop_rueckeroberung(m41)",
     'test_a6_regression', 'test_a6_e41_waiting_precedes_partial_sale_in_same_candle'),
    ('E433-cvd-key', 'backtest.py',
     '"ampel_filter", "muster_cvd", "muster_oi",',
     '"ampel_filter", "muster_oi",',
     'test_backtest', 'test_e433_zeile_unterscheidet_sich_in_genau_einem_punkt_von_live'),
    ('E434-oi-default', 'main.py',
     '    "muster_oi": "usd",\n', '',
     'test_main', 'test_alle_evaluate_parameter_werden_durchgereicht'),
    ('E434-oi-key', 'backtest.py',
     '"ampel_filter", "muster_cvd", "muster_oi",',
     '"ampel_filter", "muster_cvd",',
     'test_backtest', 'test_e434_zeile_unterscheidet_sich_in_genau_einem_punkt_von_live'),
]

# Extra historical text templates whose current implementation moved or acquired
# the A2 provenance guard. IDs retain their original place in the 316-case list.
REFRESH_EXTRA = [
    ('sabotage_e41:016', 'strategy_core.py',
     '                elif stop_grund:\n                    reason = stop_grund',
     '                elif False:\n                    reason = stop_grund',
     'test_strategy_core', 'test_e41_rueckeroberung_ueberlebt_den_stich_und_stoppt_beim_zweiten_bruch'),
    ('sabotage_e41:019', 'position_state.py',
     "if f.name not in TRANSIENT | {'state', 'zones'}",
     "if f.name not in TRANSIENT | {'state', 'zones', 'stop_wartet'}",
     'test_main', 'test_e41_warten_ueberlebt_den_neustart_der_live_engine'),
    ('sabotage_e41:020', 'position_state.py',
     '            setattr(pos, f.name, deepcopy(d[f.name]))',
     "            if f.name != 'stop_geprueft': setattr(pos, f.name, deepcopy(d[f.name]))",
     'test_main', 'test_e41_warten_ueberlebt_den_neustart_der_live_engine'),
    ('sabotage_e43:001', 'strategy_core.py',
     '_of_reihe(_fut_cvd_usd(candles, flow), fenster)',
     '_of_reihe([p.fut_cvd for p in flow], fenster)',
     'test_main', 'test_futures_cvd_rechnet_jede_kerze_mit_ihrem_eigenen_kurs'),
    ('sabotage_e433:005', 'strategy_core.py',
     'cvd_pump and oi_valid and oi_chg >= 0.03',
     'cvd_pump and oi_valid and oi_chg >= 0.3',
     'test_strategy_core', 'test_e433_usd_erkennt_den_pump_in_dollar'),
    ('sabotage_e433:009', 'strategy_core.py',
     'spot = f[-1].spot_cvd - f[0].spot_cvd',
     'spot = (f[-1].spot_cvd - f[0].spot_cvd) / abs(f[0].spot_cvd or 1)',
     'test_a6_regression', 'test_a6_cvd_window_dollars_ignore_arbitrary_start'),
    ('sabotage_e433:011', 'strategy_core.py',
     'd[0] <= d[1] / 3', 'd[0] >= d[1] / 3',
     'test_strategy_core', 'test_e433_usd_erkennt_den_pump_in_dollar'),
    ('sabotage_e433:012', 'strategy_core.py',
     'd[0] <= d[1] / 3', 'd[0] <= d[1]',
     'test_strategy_core', 'test_e433_usd_erkennt_den_pump_in_dollar'),
    ('sabotage_e433:013', 'strategy_core.py',
     'd[1] > 0 and d[0] <= d[1] / 3', 'd[0] <= d[1] / 3',
     'test_strategy_core', 'test_e433_fallende_futures_sind_kein_pump'),
    ('sabotage_e434:001', 'strategy_core.py',
     'if muster_oi == "btc":', 'if muster_oi == "BTC":',
     'test_strategy_core', 'test_e434_muster_oi_kommt_in_evaluate_an'),
    ('sabotage_e434:008', 'strategy_core.py',
     'oi_valid and oi_chg <= -oi_wipeout_pct',
     'oi_valid and oi_aenderung(f) <= -oi_wipeout_pct',
     'test_strategy_core', 'test_e434_vorprobe_demo_oi_usd_erkennt_am_kurs'),
    ('sabotage_e434:009', 'strategy_core.py',
     'oi_valid and oi_chg >= -0.01',
     'oi_valid and oi_aenderung(f) >= -0.01',
     'test_strategy_core', 'test_e434_btc_wirkt_in_allen_mustern_die_das_oi_lesen'),
    ('sabotage_e434:010', 'strategy_core.py',
     'oi_valid and oi_chg <= -0.02',
     'oi_valid and oi_aenderung(f) <= -0.02',
     'test_strategy_core', 'test_e434_btc_wirkt_in_allen_mustern_die_das_oi_lesen'),
    ('sabotage_e434:011', 'strategy_core.py',
     'cvd_pump and oi_valid and oi_chg >= 0.03',
     'cvd_pump and oi_valid and oi_aenderung(f) >= 0.03',
     'test_strategy_core', 'test_e434_vorprobe_demo_oi_usd_erkennt_am_kurs'),
    ('sabotage_e434:012', 'strategy_core.py',
     'oi_valid and 0 <= oi_chg <= 0.10',
     'oi_valid and 0 <= oi_aenderung(f) <= 0.10',
     'test_strategy_core', 'test_e434_btc_wirkt_in_allen_mustern_die_das_oi_lesen'),
    ('sabotage_e434b:003', 'strategy_core.py',
     '_of_reihe([p.oi_btc for p in flow], fenster)',
     '_of_reihe([p.oi for p in flow], fenster)',
     'test_strategy_core', 'test_e434b_echte_kontrakt_aenderung_bleibt_sichtbar'),
    ('sabotage_e443:026', 'strategy_core.py',
     "                _reset_position(pos)\n                pos.last_stop_ts = cur.ts\n                _e42_ende()",
     "                pass\n                pos.last_stop_ts = cur.ts\n                _e42_ende()",
     'test_e443', 'test_aus_flat_stop_des_teils_ist_voller_ausstieg'),
    ('sabotage_e443:028', 'position_state.py',
     "if f.name not in TRANSIENT | {'state', 'zones'}",
     "if f.name not in TRANSIENT | {'state', 'zones', 'e42_teil_wartet'}",
     'test_e443', 'test_zustand_ueberlebt_den_neustart_der_live_engine'),
    ('sabotage_e443:029', 'position_state.py',
     '            setattr(pos, f.name, deepcopy(d[f.name]))',
     "            if f.name != 'e42_ausbruch_ts': setattr(pos, f.name, deepcopy(d[f.name]))",
     'test_e443', 'test_zustand_ueberlebt_den_neustart_der_live_engine'),
    ('sabotage_e443:030', 'position_state.py',
     "if f.name not in TRANSIENT | {'state', 'zones'}",
     "if f.name not in TRANSIENT | {'state', 'zones', 'e42_gekauft'}",
     'test_e443', 'test_zustand_ueberlebt_den_neustart_der_live_engine'),
    ('sabotage_e443:031', 'position_state.py',
     "if f.name not in TRANSIENT | {'state', 'zones'}",
     "if f.name not in TRANSIENT | {'state', 'zones', 'bestand_pct'}",
     'test_e443', 'test_zustand_ueberlebt_den_neustart_der_live_engine'),
    ('sabotage_e443:033', 'main.py',
     '        for j, m in enumerate(m42):',
     '        for j, m in enumerate([]):',
     'test_e443', 'test_live_meldungen_stehen_je_kerze_vor_ihren_signalen'),
    ('sabotage_e443:034', 'main.py',
     "        if sigs:\n            for j, sig in enumerate(sigs):\n                stage('signal', sig['ts'], j, sig, format_signal(sig),\n                      lambda sig=sig: send_signals([sig], dry_run=True))",
     "    for _a, _b, sigs in pakete:\n        if sigs:\n            for j, sig in enumerate(sigs):\n                stage('signal', sig['ts'], j, sig, format_signal(sig),\n                      lambda sig=sig: send_signals([sig], dry_run=True))",
     'test_e443', 'test_live_meldungen_stehen_je_kerze_vor_ihren_signalen'),
]


def cases():
    result = [dict(id='contract:' + name, script='A1-A5/T01', name=name,
                 file=file, old=old, new=new, preferred_test=test,
                 preferred_module=module)
            for name, file, old, new, module, test in CASES]
    result += [dict(id='refresh:' + name, script='T01-refreshed', name=name,
                    file=file, old=old, new=new, preferred_test=test,
                    preferred_module=module)
               for name, file, old, new, module, test in REFRESH]
    result += [dict(id='current:' + origin, origin_id=origin,
                    script='T01-current-equivalent', name=origin,
                    file=file, old=old, new=new, preferred_test=test,
                    preferred_module=module)
               for origin, file, old, new, module, test in REFRESH_EXTRA]
    return result
